[package]
name = "luxinos"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "guessing-game-server"
path = "src/server.rs"

[[bin]]
name = "guessing-game-client"
path = "src/client.rs"
